### ISSUE TITLE
Better visual desing

### ISSUE THREAD

**Issue by ai** [andywer/postcss-debug#8] opened 2016-06-02 10:54 UTC
Out current UX is nice, but we need better visual design:
1. Better fonts
2. More modern controls

We could always try Material design, its visual langauge pretty nice and better then nothing (but custom visual design will be nicer).

With better visual design this tool will look more professional.

**Comment by Gaserd** [comment] 2016-06-02 11:22
We can try Material design, but i dont like material design :) 
What you like fonts ? Current font - Roboto, san-serif.

**Comment by ai** [comment] 2016-06-02 11:37
Yeap, I agree that Metarial is to mainstream :).

Hm, maybe font problem is already closed.

**Comment by Gaserd** [comment] 2016-06-02 11:41
We can try, and see -> good Material design or not good :) In our case

**Comment by Gaserd** [comment] 2016-06-02 14:16
I make Material design, but dont make "code area"

ScreenShot : 
![2016-06-02 17 14 31](https://cloud.githubusercontent.com/assets/5616006/15747938/9b4559ca-28e5-11e6-81aa-18e0497ec161.png)

**Comment by ai** [comment] 2016-06-02 14:20
I like it. And it doesn't look too material, which is cool.

Links to documentation is nice idea.

We need to return info badge to plugins.

There is only one UX issue right now: we don't show that plugins are inside opened file. Maybe we should make files aside like app left menu panel with full height from header to bottom of the page?

**Comment by andywer** [comment] 2016-06-02 14:33
Yeah, looks nice, yet not too materialish.

@Gaserd What's the difference between 'Documentation' & 'GitHub'? The only documentation right now is on github 😅
@ai What do you mean by "we don't show that plugins are inside opened file"?

**Comment by ai** [comment] 2016-06-02 14:36
@andywer I mean, that we don't show clicking on file will reload plugin sections. That plugins is a content of current file.

**Comment by Gaserd** [comment] 2016-06-02 14:38
@ai  @andywer Ok. I think about this

**Comment by Gaserd** [comment] 2016-06-02 17:45
@andywer  @ai
I make this.

1 - Under the heading "file" show plugins
2 - Under the heading "plugin" show small text about this plugins and click this text go to npm

![2016-06-02 20 36 22](https://cloud.githubusercontent.com/assets/5616006/15754720/443a30d4-2902-11e6-9f61-a9137e3c809e.png)

**Comment by andywer** [comment] 2016-06-02 17:52
@Gaserd Interesting, but I see two problems... First, the executed plugins will be the same for all files, so showing there should be no need to show them for every file separately.

Secondly, showing some description text for the plugin is way more complicated then just linking to it. Not impossible, but a lot of effort.

**Comment by Gaserd** [comment] 2016-06-02 17:55
@andywer hm hm hm.

**Comment by Gaserd** [comment] 2016-06-02 18:02
@andywer back (?) for link npm ? :)

But,user may be use different plugins for different files

**Comment by andywer** [comment] 2016-06-02 18:47
@Gaserd You run postcss on your files with using some set of plugins, but you cannot change the plugins array during execution, so in practice there cannot be different plugins for different files. At least I cannot see a way to accomplish that.

Problem with the description is that we would need to fetch the package.json (or the github landing page) of each plugin used to get the description. Creating the link was simple: `https://www.npmjs.com/package/${pluginName}`

**Comment by Gaserd** [comment] 2016-06-02 19:09
@andywer Okay 👍

**Comment by ai** [comment] 2016-06-02 19:44
We could try to take plugin description by:

```
let pkg = require('PLUGIN/package.json')
pkg.description
```

**Comment by andywer** [comment] 2016-06-02 19:59
@ai I fear that's not going to work, since this would be resolved to `path/to/postcss-debug/node_modules/PLUGIN/package.json`...

**Comment by ai** [comment] 2016-06-02 20:42
@andywer you don’t need to resolve, npm will do it for you. `require('plugin')` works, so `require('plugin/package.json')` will work too.

**Comment by ai** [comment] 2016-06-02 20:42
@andywer if you don’t start path from `./` npm will automatically find directory. this is why you could write `require('postcss/parse')` too

**Comment by andywer** [comment] 2016-06-02 20:52
@ai I am speaking of how node resolves when requiring like `require('foo/file.ext')`. If you don't start with `./` it will look for `foo/file.ext` in `path.join(__dirname, 'node_modules')`. Since postcss-debugger source files are not in your project directory where you have your CSS files, it will not find the plugin.

Or am I missing something else?

**Comment by ai** [comment] 2016-06-02 21:03
@andywer node.js will look at `./node_modules`, if it will not find file it will look then in `../node_modules`, then in `../../node_modules/` and in all other dirs.

So it will find plugin in most of cases. Especially if plugin is in project `package.json`.

Also in npm@3 all modules are in flat `node_modules`.

**Comment by andywer** [comment] 2016-06-02 21:08
@ai Ahh, you know what? I think we had two different use cases in mind...
You were rather thinking of a locally installed postcss-debug used by code (I guess) and I was thinking of a globally installed postcss-debug used via CLI :)

**Comment by ai** [comment] 2016-06-02 21:09
@andywer global npm install is evil :)

**Comment by andywer** [comment] 2016-06-02 21:16
@ai Haha! Fair enough ;)

**Comment by Gaserd** [comment] 2016-06-03 08:04
- added link for plugin under headline plugin
- added time for plugin
- added time for file
- added size file
- added button fullscreen for code block
- added full path for file
- fix small padding and margin

![2016-06-03 11 01 35](https://cloud.githubusercontent.com/assets/5616006/15772644/e571d308-297a-11e6-8cb8-a193aeaac868.png)

**Comment by Gaserd** [comment] 2016-06-03 08:28
- added DarkTheme
  ![2016-06-03 11 27 58](https://cloud.githubusercontent.com/assets/5616006/15773196/47bcff4e-297e-11e6-91c9-0568cbc577dc.png)

**Comment by andywer** [comment] 2016-06-03 08:49
Looks cool, but I think we should stick to one theme. Maybe open a twitter poll on which theme to use?

**Comment by Gaserd** [comment] 2016-06-03 09:07
@andywer I think about switch theme. Pressed Ctrl+D and switched theme, but you can open twitter poll on which theme :)

**Comment by andywer** [comment] 2016-06-03 09:20
@Gaserd Sounds nice, but it's still a small debugging utility. Let's not over-engineer :)

**Comment by Gaserd** [comment] 2016-06-03 09:27
@andywer it is now a small debugging utillity, tommorow it is a big project about it all speaking 👍

**Comment by Gaserd** [comment] 2016-06-03 09:48
Start twitter poll about themes. This is will  fun 👍

**Comment by ai** [comment] 2016-06-03 10:12
@Gaserd awesome! should we show start-end file fize?

**Comment by andywer** [comment] 2016-06-03 10:15
https://twitter.com/andywritescode/status/738675228491010048

**Comment by ai** [comment] 2016-06-03 10:15
@andywer twitter poll! Any mention of tools increase popularity.

But don’t forget ping me with a link to RTs

**Comment by Gaserd** [comment] 2016-06-03 10:16
@ai I think about this :) And I started make this UI in HTML, CSS

**Comment by ai** [comment] 2016-06-03 10:16
@andywer can you repost tweet with `[Poll]` text in tweet (many clients still don’t show a poll in tweet block and user need to know that it is a poll). Also if you remove a hash-tag and user mentions (`@PostCSS @gaserd123`) it will increase readability

**Comment by andywer** [comment] 2016-06-03 10:36
@ai @Gaserd Deleted old tweet and created a new one.

**Comment by ai** [comment] 2016-06-03 10:39
@andywer thanks :) I also scheduled post in Russian Facebook (we have a community there)

**Comment by Gaserd** [comment] 2016-06-03 10:39
@andywer Good 👍

**Comment by Gaserd** [comment] 2016-06-04 20:34
What think about this logo ? @ai  @andywer 
![2016-06-04 23 31 31](https://cloud.githubusercontent.com/assets/5616006/15801926/b0b50aa8-2aac-11e6-9a1b-882c09d34beb.png)

**Comment by ai** [comment] 2016-06-04 20:40
Monochrome version will be better, because you have no green colors in UI.

**Comment by andywer** [comment] 2016-06-05 07:55
@ai I agree, monochrome would be better. Or maybe black and white and a color we already use (but I am not a designer, so feel free to ignore).

I think it looks nice, but what is it? Not sure if it's a camera 😅

**Comment by Gaserd** [comment] 2016-06-05 08:59
@andywer this is head cosmonaut 👍

**Comment by Gaserd** [comment] 2016-06-08 07:41
May be create twitter post about new icon for PostCSS-webdebugger ?
@ai  @andywer

**Comment by ai** [comment] 2016-06-08 07:42
Yeap, more tweets 😊👍

**Comment by Gaserd** [comment] 2016-06-08 08:26
Okay, wait Andy ? Or maybe I create tweet of new icon for PostCSS-webdebugger?

**Comment by andywer** [comment] 2016-06-08 08:59
@Gaserd Do you mean if you should wait until I finish merging? We could tweet once about the new icon (before finalizing the updated design) and tweet a 2nd time when the new release is out ;)

**Comment by Gaserd** [comment] 2016-06-08 09:05
@andywer Yes, i waiting your merging 👍  And you are right, create tweet when the new release UI. But we will to increase interest for our plugin if we will create more tweets our changes for UI or Core, even if this changes very small

**Comment by ai** [comment] 2016-06-08 09:08
> we will to increase interest for our plugin if we will create more tweets our changes for UI or Core, even if this changes very small

Yeap, it is how marketing works :)

**Comment by Gaserd** [comment] 2016-06-08 09:28
@ai Yeah 👍

**Comment by Gaserd** [comment] 2016-06-08 09:35
Tweet:
https://twitter.com/gaserd123/status/740477326497054724

**Comment by andywer** [comment] 2016-06-08 17:29
Did you get any feedback yet?

**Comment by Gaserd** [comment] 2016-06-08 20:40
@andywer Yes, and i will change logo, because all dont understand what is this

**Comment by Gaserd** [comment] 2016-06-10 09:02
@ai  @andywer Maybe Gothic-Diablo style ?

![2016-06-10 12 01 31](https://cloud.githubusercontent.com/assets/5616006/15959379/2895686a-2f03-11e6-85cc-524b2b16d548.png)

**Comment by ai** [comment] 2016-06-10 09:03
@Gaserd :D strage look.

**Comment by andywer** [comment] 2016-06-10 09:38
@Gaserd Haha :'D

**Comment by Gaserd** [comment] 2016-06-14 07:13
@ai @andywer I think we leave our current icon 👍  And in future we have make new icon for this plugin, because I dont have idea for icon

**Comment by andywer** [comment] 2016-06-14 08:06
@Gaserd Seems fair. But can we make it monochrome? ;)

PS: We can collect ideas here: https://github.com/andywer/postcss-debug/issues/12

**Comment by Gaserd** [comment] 2016-06-14 08:27
@andywer  you could insert PostCSS logo in white color ?

**Comment by Gaserd** [comment] 2016-06-17 11:05
@ai @andywer added small fix in mobile UI

![2016-06-17 14 05 02](https://cloud.githubusercontent.com/assets/5616006/16148802/9794b806-3494-11e6-8a41-6c185087b1ed.png)
![2016-06-17 14 05 19](https://cloud.githubusercontent.com/assets/5616006/16148803/97950f5e-3494-11e6-977d-8987846f22a4.png)
![2016-06-17 14 05 29](https://cloud.githubusercontent.com/assets/5616006/16148804/97954f64-3494-11e6-82af-044fab33100b.png)

**Comment by ai** [comment] 2016-06-17 11:20
@Gaserd it is hard to understand that click on file block change plugin list. They looks like similar links. People will ask: “why nothing changed after I clicked on file block”

**Comment by Gaserd** [comment] 2016-06-17 13:40
@ai Okay.
![pokerface](https://cloud.githubusercontent.com/assets/5616006/16152361/3abcca18-34aa-11e6-8a90-2391d0c12fe0.jpg)

**Comment by andywer** [comment] 2016-06-17 14:16
@Gaserd You are doing great work here! I wasn't sure if anyone really uses a debugging utility on their phone, but... It will be pretty cool for demoing!

We should put the inspector with some sample code in `gh-pages` so people can try it out without installing it and it will even be usable when they try it on their iPhone :)

**Comment by Gaserd** [comment] 2016-06-17 14:38
@andywer Thanks and you are right!

**Comment by Gaserd** [comment] 2016-06-30 13:13
@andywer are you life ?

**Comment by andywer** [comment] 2016-06-30 15:18
@Gaserd Hey! Sorry for the delay. On one hand I have have been very busy the past days, on the other hand I guess I planned too much for the next release.

Here is the current roadmap:
1. Come up with postcss-debug webpack plugin (https://github.com/andywer/postcss-debug/issues/11)
2. Use webpack for the inspector
3. Use CSS modules and refactor styles (they have become really messy already)
4. Use stylelint
5. Put a sample installation on gh-pages

I should probably cut it down in favor of releasing soon.

**Comment by Gaserd** [comment] 2016-07-01 21:44
@andywer Awesome! I can you help ?

**Comment by andywer** [comment] 2016-07-02 14:31
@Gaserd I wish I could share some work on this, but I think this kind of refactoring requires too much insight into the code.

**Comment by Gaserd** [comment] 2016-07-04 10:03
@andywer okay :)

**Comment by andywer** [comment] 2016-07-04 20:05
@Gaserd I just recognized we still need a solution to prevent accidentally clicking the plugin documentation link when you want to expand a snapshot. This happens to me permanently when using the latest (not yet released) UI.

**Comment by Gaserd** [comment] 2016-07-04 21:06
@andywer https://github.com/andywer/postcss-debug/compare/a4d140e2f0...44980a1d2b#diff-66d5b211acafc61a9b202fc438dc503eR46 see it. Delete "ы"

**Comment by Gaserd** [comment] 2016-07-26 10:49
@andywer are you live ? :)

**Comment by andywer** [comment] 2016-08-01 18:27
Hey @Gaserd. Yes, I am, but I was on holidays last week ;)

There are currently still two issues left:
- Usability: Plugin help link will now often be accidentally clicked (https://github.com/andywer/postcss-debug/pull/10#issuecomment-227008044)
- Styles: The CSS files have grown wild and are pretty much unmaintainable now. Not sure how to solve this without re-writing the stylesheets completely... :-/

Sorry for the long delay!

**Comment by Gaserd** [comment] 2016-08-02 12:48
@andywer Ow!
Maybe I help you with CSS yet you write nice core code ?
Push (commit) master branch and go write nice code
:)

**Comment by andywer** [comment] 2016-08-03 12:59
@Gaserd Not sure if I got you right... Do you mean you can clean up the CSS? The problem is that I want to fix stuff before merging to master, since the master branch should always remain "clean(ish)".

And... we still have to come up with a solution for

> Usability: Plugin help link will now often be accidentally clicked (#10 (comment))

Because that will annoy users a lot, I think.

**Comment by Gaserd** [comment] 2016-08-03 13:23
@andywer Yeah, I sure can clean CSS. 
I think about this problem: 

> Plugin help link will now often be accidentally clicked (#10 (comment))

I start today clean CSS in develop branch.

**Comment by Gaserd** [comment] 2016-08-07 09:11
@ai @andywer 

> Plugin help link will now often be accidentally clicked (#10 (comment))

i think we can make so

![2016-08-07 12 04 20](https://cloud.githubusercontent.com/assets/5616006/17461503/3fc41bfa-5c97-11e6-934e-1b14572d8a26.png)

**Comment by Gaserd** [comment] 2016-08-07 09:13
@ai @andywer 

> Plugin help link will now often be accidentally clicked (#10 (comment))

I think we can make so

![2016-08-07 12 11 46](https://cloud.githubusercontent.com/assets/5616006/17461519/53664132-5c98-11e6-8ff0-de0c7a044e0c.png)

**Comment by ai** [comment] 2016-08-07 12:12
Looks good 😊

**Comment by andywer** [comment] 2016-08-07 14:26
@Gaserd Yeah, I like it to :)

**Comment by Gaserd** [comment] 2016-08-18 13:41
@ai @andywer Yeah! Congrats!

**Comment by andywer** [comment] 2016-08-18 14:01
Just published version 0.4.0 with the updated UI. Will close this issue ☀️

**Comment by andywer** [comment] 2016-08-18 14:01
Thanks @Gaserd!

**Closed as completed by andywer** 2016-08-18 14:01 UTC
